### ISSUE TITLE
if elseif on same bool

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACEpotentials.jl#10]
This line https://github.com/ACEsuit/ACE1pack.jl/blob/b1505b8d8e5ac500fcce8e8216b4c3fd41dfe223/src/read_params.jl#L20 seems to use the same logical test for the initial if and the final elseif, which seems wrong (unless julia had rather different elseif syntax compared to other languages, in which case feel free to close this issue).

**Comment by gelzinyte** [comment]
That's a typo, thanks for pointing this out.
