### ISSUE TITLE
BLR and Committees

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpotentials.jl#106]
Should the BLR solver automagically attach a committee to the model or should that be done at the `acefit!` level?  CC @wcwitt ?

**Comment by wcwitt** [comment]
It's useful to generate the committee at solve time because we can reuse any matrix factorizations. That's what I'd suggest for now

**Comment by cortner** [comment]
I think this is now done with a kwarg and shown int he tutorials.
