### ISSUE TITLE
`read_extxyz` doesn't support `energy_key`, etc anymore

### ISSUE THREAD

**Issue by gelzinyte** [ACEsuit/ACEpotentials.jl#107]
Should either 
- add this option back 
- update tutorials to reflect this change

For what it's worth, I think it's a good practice  to always label energy/force/virial entries when working with ASE, because it sometimes untransparently overwrites unlabelled ones.

**Comment by wcwitt** [comment]
Just so I understand - is this the result of a JuLIP change, or is this something I messed up when refactoring?

**Comment by gelzinyte** [comment]
I think this comes from switch to ExtXYZ (if I'm correct about this change) and them not supporting custom keys. Though I haven't followed on to this properly.

**Comment by gelzinyte** [comment]
Wait, I misunderstood - `read_extxyz` reads in all data and the correct keys are picked at `AtomsData`. I was checking if `read_extxyz` has the defaults. Do you think it's better to set default values at `ace_fit` or `AtomsData` step? Maybe the former?

**Comment by gelzinyte** [comment]
Updated the defaults to match the rest of the interface (`energy`, `force`, `virial`).
