### ISSUE TITLE
Make `acemodel` and rest of ACE1pack more consistent

### ISSUE THREAD

**Issue by gelzinyte** [ACEsuit/ACEpotentials.jl#109]
I think it would be helpful to keep default parameter values and function & parameter names consistent throughout. 

- Default `r0` in `ACE1pack.basis_params` is (very arbitrarily?) 2.5 and `_mean( rnn.(species)) ` in `acemodel`. Change `ACE1pack.basis_params` default to `_mean( rnn.(species))`?
- `model.smoothness_prior` does exactly the same thing as `regularizer.laplacian_regularizer`. Move to the same place and decide on which name to use? Also, they have different default values. 
- default weights have different defaults:
    -  `Dict("default"=>Dict("E"=>1.0, "F"=>1.0, "V"=>1.0))` in `AtomsData` and
    -   `Dict("default"=>Dict("E"=>30.0, "F"=>1.0, "V"=>1.0))` in `model.acefit!`
    
    Let's pick one? The first one has been a default for longer, but the latter has been more appropriate in my fits. That said, I don't think it matters which one is picked. 
- We have `fit.fit_ace` and `model.acefit!`. Let's at least name them `acefit` and `aceffit!` (that will break people's scripts...)? Also the latter would probably make more sense in `fit.jl`? That said, in my mind stuff in `model.jl` is more similar to `ACE1` package, so moving things out would blur that line. (again, not the most important issue)

**Comment by cortner** [comment]
This is now a bit outdated so I'm closing this in favour of a new issue #218  where we can start from scratch.
