### ISSUE TITLE
fill_defaults! requires that "type": "rad" be set in "rad_basis" dict

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACEpotentials.jl#11]
This line https://github.com/ACEsuit/ACE1pack.jl/blob/b1505b8d8e5ac500fcce8e8216b4c3fd41dfe223/src/basis.jl#L154 suggests to me that the `rad_basis` dict is not supposed to require that `"type" : "rad"` be set manually.  However, if you pass a dict like
```
{ 'weights': {'ideal':  { 'E': 10, 'F': 50, 'V': 10} },
                    'basis': { 'rpi':  {'type': 'rpi',  'species': ['Cs', 'Pb', 'Br'], 'r0': 3.0, 'rad_basis': {'rin': 2.0, 'rcut': 7.0}},
                               'pair': {'type': 'pair', 'species': ['Cs', 'Pb', 'Br'], 'r0': 3.0, 'rcut': 7.0, 'maxdeg': 3} },
                    'solver': {} }
```
to `fill_defaults!`, you get an error where it complains that the `rad_basis` dict has nothing for `type`.  Adding a `"type": "rad"` to the `rad_basis` dict fixes this, but seems like it shouldn't be necessary.  Here's the error stack trace
```
ERROR: LoadError: AssertionError: !(isnothing(type))
Stacktrace:
 [1] basis_params(; type::Nothing, kwargs::Base.Pairs{Symbol, Float64, Tuple{Symbol, Symbol}, NamedTuple{(:rin, :rcut), Tuple{Float64, Float64}}})
   @ ACE1pack ~/.julia/packages/ACE1pack/QCojp/src/basis.jl:13
 [2] _fill_default(d::Dict{String, Any}, key::String)
   @ ACE1pack ~/.julia/packages/ACE1pack/QCojp/src/read_params.jl:33
 [3] fill_defaults!(params::Dict{String, Any}; param_key::String)
   @ ACE1pack ~/.julia/packages/ACE1pack/QCojp/src/read_params.jl:12
 [4] fill_defaults!(params::Dict{String, Any}; param_key::String)
   @ ACE1pack ~/.julia/packages/ACE1pack/QCojp/src/read_params.jl:19
 [5] fill_defaults!(params::Dict{String, Any}; param_key::String)
   @ ACE1pack ~/.julia/packages/ACE1pack/QCojp/src/read_params.jl:16
 [6] fill_defaults!(params::Dict{String, Any})
   @ ACE1pack ~/.julia/packages/ACE1pack/QCojp/src/read_params.jl:12
 [7] top-level scope
   @ ~/src/work/workflow_devel/wfl/scripts/ace_fit.jl:46
in expression starting at /home/cluster2/bernstei/src/work/workflow_devel/wfl/scripts/ace_fit.jl:46
```

Is this a bug, or are we just using `fill_defaults!` wrong (in [ace_fit](https://github.com/libAtoms/workflow/blob/446c65608ee80b29a2f7a2b29594558c00b0489b/wfl/scripts/ace_fit.jl#L44))

**Comment by gelzinyte** [comment]
It's not entirely a bug - currently all bases are constructed with the same constructor, so all dictionaries must have a `type`. But I agree it shouldn't be necessary, I'll fix this together with updating `fill_defaults!` #4
