### ISSUE TITLE
Add saving to yace to `ACE1pack.fit_ace`

### ISSUE THREAD

**Issue by gelzinyte** [ACEsuit/ACEpotentials.jl#110]
Currently only .json is supported. We should look at `ACE_fname` extension and save to the corresponding format.

**Comment by gelzinyte** [comment]
We decided to save to both, `.json` and `.yace`. So instead of `ACE_fname` we will have `ACE_fname_stem` and add `.json` and `.yace` extensions. Need to remember to change the docs and potentially some artefacts.

**Comment by cortner** [comment]
Think that's good. Thank you

**Comment by wcwitt** [comment]
I think we've moved past this. We can revisit if necessary.
