### ISSUE TITLE
Update command line functionalities

### ISSUE THREAD

**Issue by gelzinyte** [ACEsuit/ACEpotentials.jl#116]
I think there have been some now-standard updates that haven't made it to the command line interface. 
- `PolyEnvelope`
- `AgnesiTransform`
- purified basis

Anything else I missed? Is anything made redundant by these?

**Comment by cortner** [comment]
I'm just in the process of completing an experimental PR in ACE1x.jl . Once this is done, I'd like to discuss how this should possibly be replaced with analogous defaults in ACE1pack. Can we wait for a few more days on this please?

**Comment by cortner** [comment]
But this is about more than just the CLI, it's also about defaults.

**Comment by wcwitt** [comment]
I've made a decent start at this in eebfb9d6e3563c7ee3a93084a36e7e6591625938 and the commits preceding it. But lots still remaining. The idea is to have a parallel command line interface that wraps `acemodel`/`acefit!`, with keyword arguments that mirroring their arguments. We can retire the old command line interface if we like.

**Comment by cortner** [comment]
I think this can be closed in view of the new discussion in  #218

**Comment by cortner** [comment]
shell functionality is now in pretty good shape for 0.8 and won't be updated for 0.6 anymore.
