### ISSUE TITLE
ACE1x

### ISSUE THREAD

**Issue by casv2** [ACEsuit/ACEpotentials.jl#117]
Pulling the registry and adding ACE1pack, and afterwards ACE1x I only get 0.0.2, but I need 0.0.4. Also for ACE1 we'll need v0.11 which is not currently part of this environment.

@cortner Are things stable enough to ship ACE1pack with these newer versions of ACE1x and ACE1? I think we really need them, such that new (HAL) users get them.

**Comment by cortner** [comment]
@wcwitt and @gelzinyte  -- how do you feel about merging `v011` and tagging it as a new minor version? My hope was to bring the new heuristics into ACE1pack first, but maybe we can just postpone that to another minor version update?

**Comment by wcwitt** [comment]
What you propose WRT ACE1pack is definitely needed, but it requires us to coordinate a bit more than is realistic this week. I think it's fine if we have two minor version updates in relatively short succession

**Comment by cortner** [comment]
Then I'll try to take care of this today

**Comment by wcwitt** [comment]
@cortner @gelzinyte @casv2 

Is it okay if I convert ACE1pack to rely fully on the new ACE1x basis and drop support for the old way? This would obviously be a breaking change and would require a new minor version. But for the sake of keeping the `json` interface (and related documentation) as simple and up-to-date as possible, I'm inclined to drop support for the old basis entirely. Let me know if that sounds too radical.

**Comment by cortner** [comment]
Are you suggesting to call `ACE1x.ace_basis` or are you suggesting you will update the defaults to construct the same basis directly in ACE1pack?  If the latter, then I agree with that. And I also agree to keep it simple. 

I would just make sure the "stakeholders" e.g. Cas, Noam confirm that they have been happy with those new basis defaults.

**Comment by wcwitt** [comment]
Haven't thought through all the details - and open to suggestions - but right now ACE1pack is split (roughly between the `json`/`params`/`fit_ace` way of doing things and the `acemodel`/`ACE1x` way). If we agree the latter is the future, I want to start updating the json interface, unit tests, documentation, etc to reflect that. And I'd vote against preserving backwards compatibility if possible.

Tagging @bernstei, since I didn't before.

**Comment by cortner** [comment]
Personally I strongly prefer the `acemodel` interface. I think it is much more transparent for a user. It should be not problem to keep the basis interface available to powerusers. They can just create an acemodel and extract the basis from it.

**Comment by cortner** [comment]
@tjjarvinen  I think you should also have a view on this?

**Comment by bernstei** [comment]
Can the acemodel interface filter out unreasonable forces?  Can it apply various weights, e.g. per atom?

`json`/`params`/`fit_ace` may not be the right interface, but given that `acemodel` sets up a design matrix, solves it, and turns the coefficients into a potential, I see no downside to making those intermediate steps accessible.

**Comment by tjjarvinen** [comment]
If it is clear how things are done in the future, then go for it. Now is the time to drop old ways out, before publishing anything.

**Comment by cortner** [comment]
I dont' think this is an issue anymore. Can be reopeneing if I'm wrong.
