### ISSUE TITLE
Add documentation instructions on how to use multithreading

### ISSUE THREAD

**Issue by tjjarvinen** [ACEsuit/ACEpotentials.jl#118]
Plotting potentials based on current documentation uses only a single thread, prints message `[ Info:   - Beginning assembly in serial mode.`

Add instructions on how to use multithreading.

**Comment by cortner** [comment]
presumably you mean how to use multi-threading for fitting? I believe this is actually not implemented, but distributed fitting is. @wcwitt can say more.

**Comment by wcwitt** [comment]
Resolved by f05c323699cd780ab3b13e794e9169406c9342e5. Currently, I've removed the serial option and ACEfit simply uses all available Julia workers, no matter what. I'm open to changing this down the road.
