### ISSUE TITLE
] add ACE1pack unsatisfiable requirements?

### ISSUE THREAD

**Issue by casv2** [ACEsuit/ACEpotentials.jl#12]
Just running `] add ACE1pack` complains about the following, is this expected? I'm not sure... It's at least unexpected to me, but if this is the correct behaviour then apologies for the false alarm.

![image](https://user-images.githubusercontent.com/37537160/156609605-935dd686-af94-43c0-bc54-65f2227a1e4c.png)

(apologies for the screenshot, apparently copy + paste messes up the formatting on Windows... ask Bill...)

**Comment by gelzinyte** [comment]
Is IPFitting pinned at `v0.5.0` (by using a development `v0.5.0`? ACE1pack is fixed at `v0.10`.
