### ISSUE TITLE
Tag 0.4?

### ISSUE THREAD

**Issue by wcwitt** [ACEsuit/ACEpotentials.jl#128]
Hi @cortner, I fear I have merged some updates to `main` prematurely, but something was necessary after bumping `ACEfit`. The good news is the tests pass now, which hasn't been the case for a while. Do you want to tag a new minor release? I suspect we will reach 0.5 by the time the paper is published, so for now I'm inclined to move quickly and fix problems as they emerge.

**Comment by cortner** [comment]
sure, I can do that. Any major changes I should be aware of?

**Comment by cortner** [comment]
done

**Comment by wcwitt** [comment]
Thanks! There are some notation changes, but to be honest I've lost track a little. I'll work hard this week to make sure the documentation is up to date at least
