### ISSUE TITLE
Repulsive Core functionality

### ISSUE THREAD

**Issue by casv2** [ACEsuit/ACEpotentials.jl#13]
It'd be nice to be able to fit repulsive cores using ACE1pack. I think this can be easily implemented by adding an optional keyword to `fit_params` where we'd give it a dictionary say `R` with the element tuples as keys and `(ri,e0)` as values which would then create a `Vrep` which we set to `IP.components[2]`.

**Comment by cortner** [comment]
I think I would bring this once we have @WillBaldwin0 's version. I don't like the spline idea at all, never really did, it was just the first thing we tried and never moved on.

**Comment by cortner** [comment]
or is this urgent?

**Comment by casv2** [comment]
Hmm, fairly urgent perhaps as I'm trying to design a protocol that returns a potential (with or without repulsive core) onto the pipeline. I can really only create and send .json's to trigger ACE.jl from their software... I can work with the current (or old) repulsive core for now though

**Comment by cortner** [comment]
ok, then maybe a quick PR to just get something that runs, but design it so that it can be easily swapped out for the new mechanism.

**Comment by wcwitt** [comment]
Can we close this now?

**Comment by cortner** [comment]
@casv2 ??
