### ISSUE TITLE
PythonCall update in ACEfit

### ISSUE THREAD

**Issue by wcwitt** [ACEsuit/ACEpotentials.jl#132]
The tests are failing now because of the switch to PythonCall in ACEfit. I've tried to fix `test_silicon.jl` (for example), but I keep getting `PythonCall`-related segfaults. Any ideas @tjjarvinen?

**Comment by tjjarvinen** [comment]
To add a TODO here.

- [x] ASE.jl needs to be either removed or changed to use PythonCall
- [x] Remove PyCall from Project.toml
- [x] Remove pip usage from CI - if we use PythonCall we should use [CondaPkg.jl](https://github.com/cjdoris/CondaPkg.jl)
- [x] Add Project.toml to tests - this is Julia recommendation that all packages should use.

Might be something more too, but this is a start

**Comment by wcwitt** [comment]
I believe #134 addressed everything here except the `pip` usage in the CI. But I don't have time to look at that just now.

**Comment by cortner** [comment]
@wcwitt  -- can we try to remove ASE.jl? Is anybody still using this?

**Comment by wcwitt** [comment]
I removed `ASE.jl` as part of #134. It seemed to improve #131, which I was glad to see. Hopefully the removal doesn't affect anyone.

**Comment by cortner** [comment]
oh great, this is already tagged as 0.4.1. And testing locally seemed fine.

**Comment by cortner** [comment]
can this be closed?

**Comment by wcwitt** [comment]
@tjjarvinen suggested this, which is fine with me, although I don't know how to do it quickly myself. Everything else is done I think.

> Remove pip usage from CI - if we use PythonCall we should use [CondaPkg.jl](https://github.com/cjdoris/CondaPkg.jl)

**Comment by tjjarvinen** [comment]
Now that ASE has been removed and ACEfit uses CondaPkg.jl for sklearn, we can just delete the pip line from CI.

**Comment by wcwitt** [comment]
Can we delete everything python-related (e.g., `- uses: actions/setup-python@v2`) and assume Conda will handle it? Or just the `pip` part?

**Comment by tjjarvinen** [comment]
We need the Python part for PythonCall tests. But we don't need to install any Python packages, as that is taken care by CondaPkg.jl.

**Comment by wcwitt** [comment]
Thanks - let's see what happens https://github.com/ACEsuit/ACE1pack.jl/pull/136.

**Comment by wcwitt** [comment]
The CI succeeded - I'll close.
