### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by gabor1** [ACEsuit/ACEpotentials.jl#138]
I just installed ACE1Pack following the detailed instructions exactly, and got this warning. 

<img width="1492" alt="image" src="https://github.com/ACEsuit/ACE1pack.jl/assets/5244647/263a3ea8-6edf-46f5-9d38-d49cc5ae5007">

**Comment by gabor1** [comment]
it was a completely fresh computer, so nothing (including Julia etc) were on it before.

**Comment by wcwitt** [comment]
Thanks - I believe this is fixed in a dev branch but I will double check and look to merge.

**Comment by wcwitt** [comment]
Resolved by #146.
