### ISSUE TITLE
JOSS Submission

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpotentials.jl#164]
... with the same list of authors?

**Comment by cortner** [comment]
@tjjarvinen  --  would you be willing to look into this please? My memory is that it needs a 1-page summary paraphrased from the software paper.

**Comment by wcwitt** [comment]
What would be the motivation here? I'm a big fan of JOSS (and review for them semi-regularly), but since we just wrote a software paper I'm not sure why we would double-up.

**Comment by cortner** [comment]
That’s a fair question. It was a plan to do this but we can revisit this. I thought it would just a give additional visibility. But maybe I’m wrong about that.

**Comment by wcwitt** [comment]
I’m not certain either way. Here’s their instructions on co-publication:
https://joss.readthedocs.io/en/latest/submitting.html#co-publication-of-science-methods-and-software

**Comment by tjjarvinen** [comment]
We could do JOSS submission, when we have the new kernels (and maybe something else too) in use. That would click the "substantial scientific effort" mark.

**Comment by cortner** [comment]
Eg Julia ecosystem integration. I’m ok with that and will close for now
