### ISSUE TITLE
Save and Load Potentials

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpotentials.jl#167]
Add a function `load_ace_potential` and `save_ace_potential`.  This needs to support typical usage from python, Julia, and in particular ACEmd. 

The main question is whether to store only the fitted calculator, or the entire `ACE1Model`, which includes the calculator as well as the basis from which it was fitted.

@tjjarvinen  --  do you have a view on that?

**Comment by tjjarvinen** [comment]
Can we evaluate the basis without ACE1 or can we move the basis to some other programs? If not, then I my opinion we should not save the basis.

**Comment by cortner** [comment]
The basis and potential are evaluated by the same codes. ACE1 right now - something else in the future.

**Comment by cortner** [comment]
I think I’m going to make it an option then we will see what is actually needed.

**Comment by cortner** [comment]
I'll add another TODO to this issue that @bernstei asked for: The entire manifest should be part of the potential to guarantee reproducable results.

**Comment by tjjarvinen** [comment]
Ok, that would mean saving manifest together with the potential or at least version information about ACE1 to the potential file.

There is also an other option - using containers. This is possible with the new ASE calculator that I now have working. This should be a lot more better option than saving manifest. And also make using (installing) ACEpotentials a lot more easier for people not familiar with Julia.

**Comment by cortner** [comment]
let's please discuss this in our next meeting. There is the immediate need of producing ACE potentials and using them in Python. But separately we will produce many other models for different problems in the future. And how to manage that?

**Comment by wcwitt** [comment]
@tjjarvinen, would you be willing to adapt a version of the potential loading routine from ACEmd and put it in ACEpotentials? It looks to me that what is needed is essentially a copy/paste of your code, removing the last bit that returns a new-style potential.

**Comment by tjjarvinen** [comment]
Yes I can do that. Do you have preferences for name?

Just to add note, calling `ACEmd.load_ace_model` with keyword argument `old_format=false` would do the same thing already. I am now presuming this is related to the Slack discussion with Noam? That option is there to implement tests between old JuLIP style potentials and new AtomsBase.

So, one option would be, to just make that call a bit more explicit that you can load JuLIP style potentials too.

**Comment by cortner** [comment]
I'm closing this in favour of a new discussion on how to save and load models, I will start a separate Issue #217
