### ISSUE TITLE
site_descriptors not defined!

### ISSUE THREAD

**Issue by tinatorabi** [ACEsuit/ACEpotentials.jl#176]
Hi! 

When trying to run https://acesuit.github.io/ACEpotentials.jl/dev/literate_tutorials/descriptor/ I get the following error:
```
ERROR: UndefVarError: `site_descriptors` not defined
Stacktrace:
 [1] top-level scope
   @ ./REPL[104]:2
   ```
My ACEpotentials is v0.6.1. site_descriptors used to be site_energy, but that doesn't seem to work anymore!

**Comment by cortner** [comment]
Thanks for flagging this - Inprobably need to register a new version.

**Comment by wcwitt** [comment]
> need to register a new version

Yes I think this is the explanation. @tinatorabi, in the meantime, you'll need to work with the `dev`d version.

**Comment by cortner** [comment]
please update your environment to make sure you have ACEpotentials@0.6.2, then try again. Report back if you still have a problem (or close if resolved)

**Comment by tinatorabi** [comment]
Just updated my env! Now everything works perfectly!
