### ISSUE TITLE
New ACE Kernels

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpotentials.jl#188]
As a first step towards retiring ACE1 entirely, I'm putting together a new evaluator (currently in a private repo). For now, it does the following: 
- evaluate radial basis via SVector splines 
- sphericart spherical harmonics 
- pooling via P4ML
- StaticPolynomials for the n-correlations
-  import ACE1 potentials into the new format (correctly!)

This next issue is to incorporate this here, provide wrappers for both JuLIP and AtomsBase (Molly), and move then discuss how to move over the entire ecosystem, I'm collecting some todos:  
- [x] switch ACE1 over to using splines for the radial basis so that fewer points can be used
- [x] also implement the entire basis sets with the new kernels
- [ ] bring the purification to the new setting

**Comment by cortner** [comment]
The evaluator is ready to incorporate here. I'd like to get feedback on the following question: Should it continue to live in a separate repo, or should I move the code into `ACEpotentials.jl` with the idea that it will localize the development, maybe simplify maintenance going forward, and be less confusing for outside users? 

CC @casv2 @wcwitt @tjjarvinen

**Comment by wcwitt** [comment]
I would be happy if we started to localize, but I also don't feel super strongly.

**Comment by tjjarvinen** [comment]
So it has the evaluator and now needs pairlist and atomic structure data input?

To aswer I would need to know a more details on what kind of input it takes etc.

For the start I would not pull it in ACEpotentials. I would first at least do some preliminary implementation for JuLIP and AtomsBase first before PR. Also, how does this stand with JuLIP retire plan?

**Comment by cortner** [comment]
The new evaluator doesn't need JuLIP but can get a JuLIP wrapper.

**Comment by cortner** [comment]
Structure and pairlisz can be anything. Needs a wrapper though.

**Comment by tjjarvinen** [comment]
Then ACEmd might be a better place for AtomsBase wrapper.

Does it calculate per atom inputs or does it take a group atoms at once?

**Comment by cortner** [comment]
at the moment it does per-atom. I want to start experimenting with groups of 16 or 32, ...

**Comment by tjjarvinen** [comment]
per-atom implementation is very easy just change the ACEmd backend functions https://github.com/ACEsuit/ACEmd.jl/blob/main/src/backend.jl and after that you will have fully working AtomsBase implementation.

For groups we need to change more things, but it should not be much.

**Comment by cortner** [comment]
The wrapper should be easy enough. it's the kernels that concern me.

**Comment by tjjarvinen** [comment]
We can start with per-atom implementation first in ACEmd and see after that how to proceed with group evaluations.

**Comment by cortner** [comment]
I followed your ACEmd multi-threaded implementation - very easy and very elegant. Factor 2-3 faster than JuLIP and far fewer allocations.

 I agree once we have a good draft and it's been shown to be robust we can dig in and see where we can find more performance.

**Comment by cortner** [comment]
So ... while easy and elegant, unfortunately the performance is a bit worse than the naive JuLIP implementation - for "large" systems (> a few k atoms). For small systems it is similar or slightly better.
```
[ Info: Forces - Multithreaded - JuLIP
BenchmarkTools.Trial: 122 samples with 1 evaluation.
 Range (min … max):  32.745 ms … 52.820 ms  ┊ GC (min … max): 0.00% … 19.72%
 Time  (median):     41.009 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   41.006 ms ±  4.265 ms  ┊ GC (mean ± σ):  1.54% ±  4.71%

         ▃ ▆ ▁  ▃▃ ▁ █   ▆ ▁ ▆▃▆ ▁▃  ▁▆▁▃▆       ▁             
  ▄▇▄▁▁▁▄█▇█▇█▁▄██▇█▇█▇▇▄█▇█▄███▇██▁▄█████▇▄▇▁▄▄▄█▁▁▁▁▄▄▁▄▄▄▇ ▄
  32.7 ms         Histogram: frequency by time        50.6 ms <

 Memory estimate: 10.19 MiB, allocs estimate: 211.
------------------------------------------------------------------------
[ Info: Forces - Single threaded - new
BenchmarkTools.Trial: 24 samples with 1 evaluation.
 Range (min … max):  207.507 ms … 219.585 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     216.502 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   214.771 ms ±   3.729 ms  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▁                                          ▁ ▄ █               
  █▁▁▁▆▆▆▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▆▁▁▁▁▁▁▆▆▆▁▁▁▁▁▁█▁█▁█▆▆▆▁▆▁▁▆▁▁▁▁▆ ▁
  208 ms           Histogram: frequency by time          220 ms <

 Memory estimate: 325.33 KiB, allocs estimate: 4.
------------------------------------------------------------------------
[ Info: Forces - Multithreaded - new
BenchmarkTools.Trial: 78 samples with 1 evaluation.
 Range (min … max):  35.884 ms … 269.521 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     60.736 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   64.836 ms ±  29.829 ms  ┊ GC (mean ± σ):  0.68% ± 5.02%

   ▁ ▁ ▃▁▁▁ ▆     █     ▆  ▆▁                                   
  ▇█▇█▄████▇█▁▄▇▁▄█▇▄▄▄▄█▇▇██▄▄▇▄▁▄▁▄▁▁▁▁▇▁▄▁▁▁▄▁▁▁▄▁▁▁▁▁▁▁▁▁▄ ▁
  35.9 ms         Histogram: frequency by time          125 ms <

 Memory estimate: 9.86 MiB, allocs estimate: 201.
```

**Comment by tjjarvinen** [comment]
The main target with the new multithreading implementation was to fix the multithreading bug. For energy evaluation this lead to a faster code, for forces the code is slower - as you found out.

There is an opportunity for improvements here and it has been on my todo list.

The lesson to lear hear is that, there is the reduction has a considerable effect on final perfomance and it should not be overlooked when we try to get the last bit of performance out.

**Comment by cortner** [comment]
There is quite a lot going on in AtomsBase, AtomsCalculators, and also in EquivariantModels right now. I will therefore keep UF_ACE separate for now, but as soon as things have settled down a bit I will move the new kernels in `ACEpotentials.jl` precisely for the purpose of localizing the development of mature / established models and help avoid confusion for users who aren't immersed in the Julia environment. Experimental models can still be kept in separate repos.

**Comment by cortner** [comment]
On the topic of new ACE kernels for the basis rather than the evaluator: If we only need the matrix-vector multiplication `A * c` then we can have this right now. This would limit us to using iterative methods such as LSQR. Do we think it is worthwhile putting this together - I would need maybe 1/2 day for it. 

to get the entire design matrix efficiently requires implementation of jacobians. This could be a lot of additional work. I can't be sure until I think about it.

**Comment by cortner** [comment]
It's a bit unclear to me now what the role of ACE1 is anymore. The new implementation started in #195 look elegant, fast, and general. I am now thinking of simply having one minor version with both ACE1 and the new kernels to give some time for testing. Then if the new models are at least as efficient and effective we just kill ACE1 and move over entirely for the next minor version.

**Comment by cortner** [comment]
#196  supercedes this.
