### ISSUE TITLE
Bring BBspec back

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpotentials.jl#204]
cc @CheukHinHoJerry

**Comment by CheukHinHoJerry** [comment]
This probably best done with a PR at `EQM` so that the `A2B` map gives an option to return the `(nn,ll)`? I can still track that via the `SparseTensor` and `AAspec` though if we don't want to change that.

**Comment by cortner** [comment]
Not necessarily. I think we can just read it off `A2Bmap`. Maybe I can try tonight.

**Comment by CheukHinHoJerry** [comment]
Right - I just realized that should be easier. I am halfway so maybe I can take care of that? Will finish it off tonight.

**Comment by CheukHinHoJerry** [comment]
Done by #205
