### ISSUE TITLE
Passing elements as tuple stalls code

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpotentials.jl#210]
This is fine: 
```julia
using ACEpotentials
model1 = acemodel(elements = [:Si,], 
                        order = 3, 
                        totaldegree = 6, 
                        rcut = 5.5,  )
```
This stalls, no error or anything just seems to run forever...
```julia
using ACEpotentials
model1 = acemodel(elements = (:Si,),  
                        order = 3, 
                        totaldegree = 6, 
                        rcut = 5.5,  )
```
We need either an error message or make it work.

**Comment by wcwitt** [comment]
Are you looking for a fix already? If not I will later today.

**Comment by cortner** [comment]
I haven't had time yet. Probably won't today. If you can make a quick PR, it would be helpful, thank you.

**Comment by cortner** [comment]
Moved to [ACE1x.jl#18](https://github.com/ACEsuit/ACE1x.jl/issues/18)
