### ISSUE TITLE
using ACEpotentials should not put ACE1.Random into global scope

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpotentials.jl#211]
This means that one can then not import the core `Random` package, which is a huge problem.

**Comment by wcwitt** [comment]
Should the fix be in ACEpotentials (which re-exports ACE1) or in ACE1, which exports ACE1.Random here: https://github.com/ACEsuit/ACE1.jl/blob/8ac52d2128241a01d8b9a036f41b1d5106cbeb07/src/ACE1.jl#L62.

**Comment by wcwitt** [comment]
I'm not sure I understand exactly what is required, but happy to do something if you suggest it.

**Comment by cortner** [comment]
I'm trying to think about whether it is worth to make a breaking change for this given that we are trying to retire ACE1 entirely. I'm currently working on achieving feature parity of the new implementation with ACE1. If I can achieve this within the next few days/weeks, then we could just close this as no longer relevant?

**Comment by cortner** [comment]
#215 implemented the necessary changes avoiding re-exporting all of  ACE1 and ACE1x on the `main` branch. I will not fix this on v0.6.x
