### ISSUE TITLE
Possible mismatch of virials sign and magitude between ML-PACE LAMMPS and JuLIP.jl implementation?

### ISSUE THREAD

**Issue by hari-ushankar** [ACEsuit/ACEpotentials.jl#212]
Hello folks,

Just wanted to confirm about the magnitude virials for ACEpotentials calculated using 
(i) ML-PACE implementation in LAMMPS  and (ii) JuLIP.jl:

(i) I have relaxed a structure using a fitted ACE model in LAMMPS (a big shoutout to @wcwitt 🎉 for their help ).

(ii) Read the potential into Julia and the final relaxed structure also, and evaluate the virials by: `ACE1.virial(struct1)`. From my understanding of definition of virial, virial = -stress * volume.

stress from lammps:
Pyz =   1698.4627  MPa

virial from JuLIP:

virial(2,3) = 3.4385 eV

volume from JuLIP: 3243.5700963735135 ang3

stress(2,3) = - 0.00106009733 eV/ang3

1 eV/ang3 --> 160217.6634 MPa

stress(2,3) = -169.846317 MPa.

so the sign and magnitude seems off. I don't know if this will be a major factor in the results. Nonetheless, I want to bring this up.

For the energies, I get good matching:

LAMMPS: -1068.6558 eV
JuLIP.jl: -1068.6557962647173 eV

For the forces,
both codes give zero forces for all atoms. This is great. 

CC: @cortner 

Attached are the LAMMPS log file for step(1) and julia script, geometry, ACE model for step(2). 

[Archive.zip](https://github.com/user-attachments/files/16369666/Archive.zip)

**Comment by wcwitt** [comment]
You are using `metal` units in LAMMPS, so the unit for pressure (and therefore stress) is Bar, not MPa. I think that answers the magnitude. https://docs.lammps.org/units.html

I'm guessing the sign is just a difference in convention (internal vs applied stress).

Please double check all this and let me know if you agree.

**Comment by hari-ushankar** [comment]
Hey @wcwitt , this is so stupid of me. For some reason, VASP uses MPa, I clearly got mixed up with LAMMPS and VASP units for pressure. You are right that LAMMPS uses bar and 1 bar = 0.1 MPa. The magnitude checks out.

For the sign convention, LAMMPS does not get into the details on the sign in the docpage:

https://docs.lammps.org/compute_pressure.html

Only thing stated is that r.F is used for virial for molecular statics. 

From ACE1 source code, I could only find this: 

https://github.com/ACEsuit/ACE1.jl/blob/8ac52d2128241a01d8b9a036f41b1d5106cbeb07/src/pairpots/pair_basis.jl#L146

There is no apparent reason for the mismatch on the sign.

I will run some tests with simple bulk geometry with larger than equilibrium lattice constant to see what signs each code gives me. This will already give me the answer. 😃 

Thank you again for your help on this. 🙏 

We can close this issue too.
