### ISSUE TITLE
Revive and redesign JSON interface

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpotentials.jl#218]
We can use this issue to discuss the revival and redesign of the JSON interface. 

CC @CheukHinHoJerry @wcwitt @gelzinyte  @iamveronika

**Comment by CheukHinHoJerry** [comment]
During fitting, would it be useful to write a logging file that output the FULL hyper-parameter dictionary with all the details of the fits for keeping record (even for random seed etc)? I found this pretty useful when working with `mace` that I can just look at the log and make sure nothing does wrong.

**Comment by cortner** [comment]
Ok for me to add this.

**Comment by cortner** [comment]
more to do re polishing but the main ideas are addressed via #231
