### ISSUE TITLE
ACE2 integration

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpotentials.jl#22]
Is it possible to integrate ACE2 into ACE1pack without clashes?

**Comment by gelzinyte** [comment]
I haven't used ACE2 before - is there an example fitting script? Maybe @davkovacs has one?

**Comment by cortner** [comment]
It's actually a question for me - sorry, I should have clarified. I'm basically wondering whether we can have both ACE1 and ACE in one wrapper code. I think this would be fantastic.

**Comment by wcwitt** [comment]
I think this originated from our conversation - my feeling is that, since we are generating a bunch of integration tests to compare ACEfit with IPFitting, we should see if we can get those same tests passing with ACE2 somehow

**Comment by cortner** [comment]
no point in having this open until we get started on this.
