### ISSUE TITLE
sklearn tests

### ISSUE THREAD

**Issue by wcwitt** [ACEsuit/ACEpotentials.jl#221]
Hi @cortner, I see you disabled some `sklearn` tests recently, possibly because they were failing with the new backend?

https://github.com/ACEsuit/ACEpotentials.jl/blob/15d12b89ea283c9d039fe8a09b3d0a6676ecceb5/test/test_silicon.jl#L104

Noam (with my help) is trying to reproduce some past fits and we need this functionality ... would it be best to work from an older ACEpotentials?

**Comment by wcwitt** [comment]
Here's the commit that disabled them: https://github.com/ACEsuit/ACEpotentials.jl/commit/f6d42d3878b72ba4cc09532116244d2df710ddf7.

**Comment by cortner** [comment]
they have been failing for a long time. It has nothing to do with the new the backend, I actually haven't retired the old backend yet. 

I disabled them because I wanted to rethink carefully about how to re-integrate SKLEARN parameter estimation. Likely through an extension or through some other generic Julia linear regression packages.

**Comment by wcwitt** [comment]
That's helpful - maybe it has to do with the MLJ extension. I'll try to figure it out.

**Comment by wcwitt** [comment]
Tests passed here: https://github.com/ACEsuit/ACEpotentials.jl/actions/runs/9090697108

**Comment by wcwitt** [comment]
This issue will be partly addressed by https://github.com/ACEsuit/ACEfit.jl/pull/77.

> I disabled them because I wanted to rethink carefully about how to re-integrate SKLEARN parameter estimation. Likely through an extension or through some other generic Julia linear regression packages.

Happy to discuss this, but at the moment `sklearn` is available only through extensions. Although it's a little confusing because there are two routes: one utilizing PythonCall as an extension and the other through MLJ as an extension.

**Comment by cortner** [comment]
If thought about this and I'd like to avoid installing all the python dependencies for the ACEpotentials tests so would prefer not to re-instate those. If you disagree with me please re-open and we can discuss again.
