### ISSUE TITLE
Import XYZ training sets without going through ASE

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpotentials.jl#23]
CC @wcwitt

**Comment by gelzinyte** [comment]
Does this need implementing from scratch or are there tools already available, just need to be added here?

**Comment by wcwitt** [comment]
The tools are available, thanks mostly to James Kermode - and there is a rough implementation already in the acefit branch, but I'm still cleaning it up

https://github.com/ACEsuit/ACE1pack.jl/blob/ab4f12de711e9075fcdc9f96742872ede97e3fda/src/data.jl#L37

**Comment by wcwitt** [comment]
The ACEfit version accomplishes this, closing.
