### ISSUE TITLE
Replace repulsion restraint with ZBL reference

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpotentials.jl#234]

**Comment by wcwitt** [comment]
Do you have a preferred way of implementing this? I like the idea of allowing for a general "reference potential" that is subtracted before the fit, which might be ZBL, the one-body E0s, or some combination. But might also be a better way.

**Comment by cortner** [comment]
The possibility is already implemented. Just need to supply a convenient interface for it. I don't have a strong view on this yet.

**Comment by wcwitt** [comment]
Sure, I was asking about the interface and your opinion - fine if you don't have a strong view. I saw a change somewhere recently that moved in the direction of E0s as the only reference and away from the more generic approach. Wasn't sure if that was purposeful or just convenient in the moment.

**Comment by cortner** [comment]
Think the E0s (list of pairs or Dict) and ZBL (true/false)should have convenience kwargs but can be overwritten by passing a general Vref.

**Comment by cortner** [comment]
For now at least. Over time we can think about how to improve on this.

**Comment by cortner** [comment]
I've now translated the repulsion restraint (#262). Still want to add the ZBL option so we can compare the two.

**Comment by cortner** [comment]
addressed by #263  -  I'm not 100% happy with the tests, but I think it now needs to be tried on real systems before raising issues with the implementatin.
