### ISSUE TITLE
Registering Next Version

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpotentials.jl#235]
@CheukHinHoJerry and @wcwitt  --  I'd like you feedback on the following question please: 

I now have ACEpotentials v0.8-dev mostly compatible with ACE1. This is purely to confirm that it has ACE1 as a subset of its capabilities. I would now like to remove JuLIP, ACE1, ACE1x entirely from the repository and keep the compatibility only as part of the test suite. 

I see two options: 
- register the current version as 0.8.0, then remove ACE1, ACE1x, and register this as 0.9.0.
- remove ACE1, ACE1x immediately and then register as 0.8.0

I tend towards the second option as I don't really see much value keeping both implementations running in parallel now that we know they are essentially compatible. But I wanted to get 1-2 additional opinions before I proceed.

**Comment by CheukHinHoJerry** [comment]
Given that we keep compatibility tests I agree that the second option is better.

**Comment by wcwitt** [comment]
I don't think we have the energy or manpower to worry about these things too much. So do whatever seems simplest to you.

On the other hand, in addition to the compatibility tests it would be nice to ensure we can reproduce the error tables from the ACEpotentials paper.

**Comment by cortner** [comment]
Yes that's a good point. In fact I would be grateful for an extended test suite.
