### ISSUE TITLE
implement Laplacian preconditioning

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACEpotentials.jl#25]
The NiAl tutorial mentions implementing Laplacian preconditioning with
```
P = Diagonal(vcat(ACE1.scaling.(dB.basis.BB, rlap_scal)...))
```
but while `"P"` is just a dict field, the quantities needed to evaluate it are not available outside of `ACE1pack ace_fit()`.  It would be helpful if there was something that could implement this preconditioning so it can be used with `ACE1pack ace_fit()`

**Comment by gelzinyte** [comment]
I think that is possible ? Though not yet documented...

`ACE1pack`/`fit.jl`/`fit_ace(params)` can have 
```
params["P"] = Dict(type => "laplacian", rlap_scal => 1.6)
```
which gets turned into your `P` as above by `precon.jl`/`generate_precon()` and passed onto `lsqfit()` as part of the `solver` dictionary. 

`test_precon.jl` has a little example on how to get that outside of `fit_ace()`.

**Comment by bernstei** [comment]
Great.  I'll test that.

**Comment by wcwitt** [comment]
Can we close this? Or @bernstei I recall you saying something seemed off about it?

**Comment by bernstei** [comment]
Well, so far it's not doing anything except making the resulting potential JSON file huge.  I get the impression that the latter problem is fixed, and I just need to update, so any bugs leading to the former may be moot as well.  I am going to close it given that, and will open a real issue if there's a problem with the latest version.
