### ISSUE TITLE
linear_errors should be renamed

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpotentials.jl#257]
This function works for any model, not just linear models. 
- `errors`
- `compute_errors`
- `test_errors`

other suggestions?

**Comment by wcwitt** [comment]
Agree a renaming is long overdue. Probably not `test_errors`, but fine with the others.

**Comment by cortner** [comment]
I haven't registered 0.8 yet. But maybe we can just deprecate and remove the old name at 0.9. Otherwise there is so much to fix and test again ...

**Comment by cortner** [comment]
closed by #265
