### ISSUE TITLE
track convergence of BRR/ARD

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACEpotentials.jl#26]
Add an ACE1pack interface to the `verbose=True` arguments of the sklearn brr/ard code (or something)

**Comment by wcwitt** [comment]
Should be resolved by 1065b56b12ca72bb9c1569db236246e280b8499d and earlier commits, as well as related work in IPFitting. New versions are also being registered (https://github.com/JuliaMolSim/MolSim/pull/3). Closing.
