### ISSUE TITLE
Users shouldn't need to know the structure/namespaces of other packages

### ISSUE THREAD

**Issue by wcwitt** [ACEsuit/ACEpotentials.jl#27]
Things like 
```
IP = ACE1pack.JuLIP.FIO.read_dict(ACE1pack.ACE1.load_dict("./ace_potential.json")["IP"])
```
shouldn't be necessary. As a first step we should add the option (perhaps by default) to export `yace` files when fitting a potential. More generally we should try to get rid of any instances where the user needs to call JuLIP or ACE1 via ACE1pack, replacing them with small ACE1pack functions when needed..

**Comment by cortner** [comment]
I'm open to suggestions for an interface. This one isn't rocket science, just needs a good solution once and for all. I suggest we don't do stop-gap.

**Comment by cortner** [comment]
I think we've pretty much fixed this. Anything that's left can be dealt with on a case by case basis...
