### ISSUE TITLE
Can not run example jupyters

### ISSUE THREAD

**Issue by FromColleWithLove** [ACEsuit/ACEpotentials.jl#279]
I am running the tutorials jupyters but I encounter problems.
In https://github.com/ACEsuit/ACEpotentials.jl/blob/main/examples/Tutorial/ACEpotentials-Tutorial.jl i have at line https://github.com/ACEsuit/ACEpotentials.jl/blob/6b95848f3cb605531c0dc35830ff408813e11ad7/examples/Tutorial/ACEpotentials-Tutorial.jl#L85 this error:

`KeyError: key :config_type not found`

while on line https://github.com/ACEsuit/ACEpotentials.jl/blob/6b95848f3cb605531c0dc35830ff408813e11ad7/examples/Tutorial/ACEpotentials-Tutorial.jl#L112 i have:
`
MethodError: no method matching neighbourlist(::JuLIP.Atoms{Float64}, ::Quantity{Float64, 𝐋, Unitful.FreeUnits{(Å,), 𝐋, nothing}}; recompute::Bool`

In https://github.com/ACEsuit/ACEpotentials.jl/blob/main/examples/Tutorial/ACE%2BAtomsBase.jl i have at 
https://github.com/ACEsuit/ACEpotentials.jl/blob/6b95848f3cb605531c0dc35830ff408813e11ad7/examples/Tutorial/ACE%2BAtomsBase.jl#L25C1-L25C24  
the error:

```
Activating project at `[~/Calcolo/acetutorial](http://localhost:8888/lab/tree/Calcolo/acetutorial/Calcolo/acetutorial)`
   Resolving package versions...
  No Changes to `[~/Calcolo/acetutorial/Project.toml](http://localhost:8888/lab/tree/Calcolo/acetutorial/Calcolo/acetutorial/Project.toml)`
  No Changes to `[~/Calcolo/acetutorial/Manifest.toml](http://localhost:8888/lab/tree/Calcolo/acetutorial/Calcolo/acetutorial/Manifest.toml)`
     Cloning registry from "https://github.com/ACEsuit/ACEregistry"
Registry `ACE` already exists in `~/.julia/registries/ACE`.
   Resolving package versions...

Unsatisfiable requirements detected for package GeomOpt [ca147568]:
 GeomOpt [ca147568] log:
 ├─possible versions are: 0.0.1-0.0.5 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions: 0.0.1-0.0.5
 ├─restricted by compatibility requirements with AtomsCalculators [a3e0e189] to versions: 0.0.5 or uninstalled, leaving only versions: 0.0.5
 │ └─AtomsCalculators [a3e0e189] log:
 │   ├─possible versions are: 0.1.0-0.2.2 or uninstalled
 │   ├─restricted to versions * by an explicit requirement, leaving only versions: 0.1.0-0.2.2
 │   └─restricted by compatibility requirements with AtomsCalculatorsUtilities [9855a07e] to versions: 0.2.0-0.2.2
 │     └─AtomsCalculatorsUtilities [9855a07e] log:
 │       ├─possible versions are: 0.1.0-0.1.5 or uninstalled
 │       └─restricted to versions * by an explicit requirement, leaving only versions: 0.1.0-0.1.5
 └─restricted by compatibility requirements with AtomsBase [a963bdd2] to versions: 0.0.1-0.0.4 or uninstalled — no versions left
   └─AtomsBase [a963bdd2] log:
     ├─possible versions are: 0.1.0-0.4.2 or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions: 0.1.0-0.4.2
     ├─restricted by compatibility requirements with AtomsBuilder [f5cc8831] to versions: 0.3.5-0.4.2
     │ └─AtomsBuilder [f5cc8831] log:
     │   ├─possible versions are: 0.0.1-0.2.1 or uninstalled
     │   └─restricted to versions * by an explicit requirement, leaving only versions: 0.0.1-0.2.1
     └─restricted by compatibility requirements with AtomsIO [1692102d] to versions: 0.3.0-0.3.5, leaving only versions: 0.3.5
       └─AtomsIO [1692102d] log:
         ├─possible versions are: 0.1.0-0.2.3 or uninstalled
         ├─restricted to versions * by an explicit requirement, leaving only versions: 0.1.0-0.2.3
         └─restricted by compatibility requirements with AtomsBase [a963bdd2] to versions: 0.1.3-0.2.3 or uninstalled, leaving only versions: 0.1.3-0.2.3
           └─AtomsBase [a963bdd2] log: see above

```

For clarity, the output of
`versioninfo() ; Pkg.status()`

is:
 
```
Julia Version 1.10.6
Commit 67dffc4a8ae (2024-10-28 12:23 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 7730U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver3)
Threads: 1 default, 0 interactive, 1 GC (on 16 virtual cores)
Environment:
  JULIA_PROJECT = /home/dalimonti/Calcolo/acetutorial
Status `~/Calcolo/acetutorial/Project.toml`
⌃ [3b96b61c] ACEpotentials v0.6.5
⌅ [a963bdd2] AtomsBase v0.3.5
⌃ [f5cc8831] AtomsBuilder v0.1.0
  [a3e0e189] AtomsCalculators v0.2.2
⌃ [9855a07e] AtomsCalculatorsUtilities v0.1.4
  [1692102d] AtomsIO v0.2.3
⌅ [352459e4] ExtXYZ v0.1.14
  [7073ff75] IJulia v1.25.0
⌅ [945c410c] JuLIP v0.14.8
  [b964fa9f] LaTeXStrings v1.4.0
⌃ [aa0f7f06] Molly v0.21.1
  [6f286f6a] MultivariateStats v0.10.3
  [91a5bcdd] Plots v1.40.8
  [03c4bcba] Polynomials4ML v0.3.1
  [08abe8d2] PrettyTables v2.4.0
  [fd094767] Suppressor v0.2.8
  [1986cc42] Unitful v1.21.0
  [8ba89e20] Distributed
  [37e2e46d] LinearAlgebra
Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated` 
```

**Comment by cortner** [comment]
The latest tutorials require ACEpotentials version 0.8.x

**Comment by cortner** [comment]
If you follow the instructions in the [README](https://github.com/ACEsuit/ACEpotentials.jl/blob/main/examples/Tutorial/README.md) then everything should work.

**Comment by FromColleWithLove** [comment]
@cortner 
Upgrading to 0.8.5 solved the issue. To do so, I needed to use Julia 1.11.
Please update the [README](https://github.com/ACEsuit/ACEpotentials.jl/blob/main/examples/Tutorial/README.md) removing the mention to Julia 1.10

**Comment by wcwitt** [comment]
> To do so, I needed to use Julia 1.11

I don't think this should be true - would you please explain why you think so? We regularly use 1.10 and haven't experimented much with 1.11 for this package.

**Comment by cortner** [comment]
As a matter of fact we don’t actually support 1.11 officially yet.

**Comment by FromColleWithLove** [comment]
@wcwitt I honestly don't know. You can see in the output above that ACEpotentials 0.6.5 is upgradable, showing the `^`,  yet trying to update it did nothing (not even threw errors). I tried many times with fresh installations / projects . Switching to Julia 1.11 it updated without problems....

@cortner 

> As a matter of fact we don’t actually support 1.11 officially yet.

Well, it worked! Except from exceeding my max RAM (16 GBs) when doing the refinement of the potential in the ACEpotentials.jl/examples/Tutorial/ACEpotentials-Tutorial.jl

**Comment by cortner** [comment]
If you start with a FRESH Julia project in 1.10, then there should be no issues. If this explanation  doesn’t make sense to you then please read up on how the Julia package manager works. There is a short explanation in our documentation with links to the the Pkg.jl docs.

**Comment by wcwitt** [comment]
>Except from exceeding my max RAM

Do you know which command caused this?

**Comment by FromColleWithLove** [comment]
@wcwitt 
> Do you know which command caused this?

The model refinement here:

https://github.com/ACEsuit/ACEpotentials.jl/blob/6b95848f3cb605531c0dc35830ff408813e11ad7/examples/Tutorial/ACEpotentials-Tutorial.jl#L381
