### ISSUE TITLE
Rewrite ACE1pack to make use of ACEbase file IO

### ISSUE THREAD

**Issue by gelzinyte** [ACEsuit/ACEpotentials.jl#3]
This will replace `read_params.jl`. 

Since `read_dict` converts loaded dictionaries into the appropriate composite type, I think, the code will need to be rewritten so that what are currently `*_params()` functions  are turned into `struct`s. Does that sound correct? What was the reason to use dictionaries and not structures in the first place?

**Comment by cortner** [comment]
nono - there is `read_dict` and `load_dict`. `read, write` converts, while `save, load` does the disk thing.

**Comment by cortner** [comment]
We can discuss the naming of those functions if you have views on that but I want to keep the logic.

**Comment by gelzinyte** [comment]
I don't mind the names, I think I misunderstood what you meant. Did you suggest replacing just the `JSON file -> unconverted Julia Dict` part (so  `load_dict`, but not `read_dict`) or pretty much all that is in `read_params.jl` (so use both `load_dict` and `read_dict`)?

**Comment by cortner** [comment]
`read_dict, write_dict` should not get too much use in ACE1pack. What I meant was to use 
* `JuLIP.FIO.save_dict` for writing to JSON
* `JuLIP.FIO.load_dict` for reading from JSON
And if you don't like those names, then I'm happy to change them. And tbh, this isn't really so crucial, I just like having a thin layer around something like that so we can swap out the backend if we ever need to, and to keep everything compatible between ACE1pack, ACE1, JuLIP, etc.

**Comment by gelzinyte** [comment]
okay! That's a small change, I'll update the PR.  

In my mind "write to disk" & "save to disk" and "read from disk" & "load from disk" are synonyms, so I need(ed) some slight getting used to the distinction. But I'm not sure if that's worth changing, especially if you mean beyond ACE1pack, which I guess a lot of people are using already? Also because can't think of good alternatives. _Maybe_ `parse` instead of `read` (feels like a slightly more virtual transformation one would do to data/string/information after loading from disk) and `assemble` (a dictionary has to be "assembled" from a structure ahead of saving to disk) or `prepare` instead of `write`, but these are still ambiguous, I think. 

I find YAML files more friendly than JSON, do you think that's worth adding and where if so? In `ACEbase.FIO` alongside `load_json` and `save_json`?

**Comment by cortner** [comment]
What about looking at the FileIO.jl conventions?

**Comment by cortner** [comment]
Yes adding YAML in ACEbase and JuLIP would be great! But maybe with conditional loading.
