### ISSUE TITLE
"add ACE1pack" isn't enough to be able to create ACE potential objects

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACEpotentials.jl#30]
If you follow the one liner in the ACE1pack docs the julia Pkg status shows
```
(@v1.7) pkg> st
      Status `~/.julia/environments/v1.7/Project.toml`
  [8c4e8d19] ACE1pack v0.0.2
  [51974c44] ASE v0.5.4
  [c7e460c6] ArgParse v1.1.4
  [945c410c] JuLIP v0.11.5
```

If you try to create an ACE with `read_dict` it complains about not having an implementation for `ACE1_PolyPairPot`, e.g.  However, iff you do `]add ACE1`, then `read_dict` finds the `ACE1_*` symbols and it works.

**Comment by cortner** [comment]
This should be resolved by now. Any evidence to the contrary?

**Comment by bernstei** [comment]
Not that I know of, although I haven't set up a new environment where this might happen in a long time.
