### ISSUE TITLE
ArgParse

### ISSUE THREAD

**Issue by gelzinyte** [ACEsuit/ACEpotentials.jl#43]
`ace_fit.jl` uses `ArgParse` which needs to be `add`ed by the users. What would be the best way to just have it as ACE1pack's dependency and not need for the users to install it alongside ACE1pack? 

I would have ArgParse be re-exported by ACE1pack and in the script call `using ACE1pack.ArgParse`. Any better ideas? @WillBaldwin0, @cortner, @wcwitt

**Comment by cortner** [comment]
why does it have to be added by the users? To run the cmd line  script?

**Comment by cortner** [comment]
If that's the case then your suggestion is the right thing to do I think.

**Comment by cortner** [comment]
I'm happy to tag a 0.0.4 if you want to fix this now quickly.

**Comment by gelzinyte** [comment]
> why does it have to be added by the users? To run the cmd line script?

Yes, exactly. 

Thanks, I'll open a PR shortly

**Comment by wcwitt** [comment]
This looks resolved to me, thanks @gelzinyte.
