### ISSUE TITLE
various important docs issues

### ISSUE THREAD

**Issue by WillBaldwin0** [ACEsuit/ACEpotentials.jl#47]
there are some important tings which need to be fixed in the docs:

1. For some reason the text I the one-liner hasn't updated on the website. It still says `JulIP` rather than `JuLIP` even though I think we've fixed that. I presume this will go away when we push another change to the installation file?
2. We haven't got a page telling people how to read potentials in ase. I think it got lost when we rearranged everything
3. the tutorials section is still a little confused - there are many tutorials and the LAMMPS export file is mixed in there as well. Could we rearrange this?

**Comment by cortner** [comment]
1 - please make a PR. 

3 - I don't really see the problem with this; see the [overview page](https://acesuit.github.io/ACE1pack.jl/dev/tutorials/). What would you like to have done differentlyu? 

2 - the tutorials should have another section just like the LAMMPs tutorial

**Comment by WillBaldwin0** [comment]
I will make a PR for 1 and 2. Also I realised that the landing page is missing key stuff so I'll add that. 

With respect to 2, we have two different Julia versions of the tutorial. Are you keen to keep both of them?

**Comment by cortner** [comment]
You mean one for controlling ACE1 directly, the other via ACE1pack? We talked with Elena about this and I think she prefers to keep the ACE1pack version. And I definitely need to keep the "pure" ACE1 version.

**Comment by gelzinyte** [comment]
I think Will meant that there are two in-Julia/ACE1 examples (without ACE1pack) in the docs currently. I think the most useful tutorials to keep would be command-line/JSON/ACE1pack and one of in-Julia/ACE1 (without ACE1pack).

**Comment by cortner** [comment]
I don't see a problem with that either - we make as many our as few as we like. Different tutorials have different use cases.

**Comment by cortner** [comment]
Just to follow-up on this, if you want more JSON-style tutorials, just bring them in. If you want to convert one of the ACE1-style tutorials into an ACEpack or JSON tutorial, that's all fine for me.

**Comment by WillBaldwin0** [comment]
closing this issue after #50
