### ISSUE TITLE
docs website not updating

### ISSUE THREAD

**Issue by WillBaldwin0** [ACEsuit/ACEpotentials.jl#52]
Since the most recent PR (and several before) the docs website has been refusing to update. I've noticed there are two 'annotations' under the actions tab for that PR(50). One is to do with a bad link, and the other is complaining about the doc string of `fill_defaults` I believe. 

Any ideas @cortner @gelzinyte?

**Comment by cortner** [comment]
Ok we need to stop merging if the don't ca don't buils corrwctly. We are travelling for a few days but I'll look into it as soon as I can

**Comment by wcwitt** [comment]
I just made two tweaks (905b7b2b5d45752ca4f1ff6d33fde75a84a9edb6 and 795896656fe64029b807bc2c812996b689af7b69) that resolve the 'annotation' warnings @WillBaldwin0 noticed. But the problem remains, unfortunately.

**Comment by wcwitt** [comment]
Okay, I think I found the explanation. Commit 2a5e50f75dc4a98fb78705117316bb2ed2544fb5 commented the `deploydocs` function. After restoring it in 563958b327f03d2917eed5d72e8b709328067235, the website updates again.

**Comment by cortner** [comment]
that sounds like something I might have done ... sorry about that.
