### ISSUE TITLE
Error with artifact in ACE1pack

### ISSUE THREAD

**Issue by nancy-ruoning-qiu** [ACEsuit/ACEpotentials.jl#53]
An error of `UndefVarError: artifact not defined` occurred after running the code in [TiAl tutorial ](https://acesuit.github.io/ACE1pack.jl/dev/literate_tutorials/ACE1pack_TiAl/).

```
using ACE1pack, ACE1, IPFitting

data_param_dict = data_params(
    fname = joinpath(ACE1pack.artifact("TiAl_tutorial"), "TiAl_tutorial.xyz"),
    energy_key = "energy",
    force_key = "force",
    virial_key = "virial")
```

**Comment by gelzinyte** [comment]
Seems to be running ok for me (ACE1pack v0.0.4, ACE1 v0.9.2, IPFitting v0.10.2) - would you mind sharing the versions of relevant packages?

**Comment by nancy-ruoning-qiu** [comment]
It is resolved. Thank you.
