### ISSUE TITLE
per-species or per-pair length scales

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACEpotentials.jl#6]
It appears the per-species or per-pair length scales are useful (e.g @WillBaldwin0 's perovskite phonon results), and I suspect my results would benefit.  It'd be very useful to figure out how to give access to such functionality (via Agnesi transform or some other tool) into ACE1pack.

**Comment by gelzinyte** [comment]
I agree and I would like to use something along those lines too. Do you have an example of how you are doing that currently?

**Comment by bernstei** [comment]
I don't have any examples, and in fact, it's starting to look like what @WillBaldwin0 is doing with Agnesi transforms may not actually be relevant to the reason my fits are worse than his. It's possible that this needs to remain open (or be closed and re-opened) until we decide on an actual heuristic, and then figure out how to make it available via ACE1pack.

**Comment by gelzinyte** [comment]
okay, I'll add what I'd be using and let's see what's missing from there.

**Comment by cortner** [comment]
We have had  per-pair for a long time...
