### ISSUE TITLE
New branch and tags for IPFitting version

### ISSUE THREAD

**Issue by wcwitt** [ACEsuit/ACEpotentials.jl#61]
@cortner, would you please tag v0.1.0 using the 0.1.x branch (https://github.com/ACEsuit/ACE1pack.jl/tree/0.1.x). We can use this to preserve compatibility with IPFitting.

Right now, the 0.1.x branch is even with 0.0.4 (except I've updated Project.toml). Once v0.1.0 exists, I'll backport relevant commits from the current master, and the result can become v0.1.1.

**Comment by cortner** [comment]
are you sure you want it tagged as 0.1.0? According to semver, that would mean that we then have to enforce backward compatibility. My thought was that we use 0.0.x until we are happy to abandon ANY further development on that branch. Please confirm.

CC @gelzinyte

**Comment by wcwitt** [comment]
Hearing that, I’m fine sticking with 0.0.x for now. The main thing is we
need to start splitting things up. Sounds like I should make a 0.0.x branch
from v0.0.4, do the backports, then we tag 0.0.5?

**Comment by cortner** [comment]
have we tagged 0.1.0 yet? If not then you don't need a new branch - I'll just tag that branch as 0.0.5

**Comment by wcwitt** [comment]
Just thought it would be weird to track 0.0.x versions in a branch called 0.1.x - that's all. I've now deleted the 0.1.x branch, created a [0.0.x branch](https://github.com/ACEsuit/ACE1pack.jl/tree/0.0.x) from Julia version `0.0.4`, and backported all the subsequent commits that don't relate to ACEfit.

So I think we're ready for you to tag 0.0.5 from the 0.0.x branch.

So far we haven't tagged any git versions in ACE1pack, but I think we should start doing so. I've been playing around a bit, and I think that's a prerequisite for being able to select specific versions of the docs on the website.

**Comment by cortner** [comment]
done
