### ISSUE TITLE
Tagging 0.0.6

### ISSUE THREAD

**Issue by wcwitt** [ACEsuit/ACEpotentials.jl#70]
@cortner, would you please tag v0.0.6?

The changes include updated compatibility bounds for IPFitting (to ensure we get the newest version with its own updated version bounds), as well as a test for the `ace_fit.jl` script.

**Comment by wcwitt** [comment]
@cortner, friendly bump.

**Comment by cortner** [comment]
done - I'm sorry I missed this, please feel free to bump me more regularly and in multiple locations.
