### ISSUE TITLE
set number of blas threads more widely

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACEpotentials.jl#71]
https://github.com/ACEsuit/ACE1pack.jl/blob/a51295085a9fe45ea588d8cfb81a9fcb3f009e1a/scripts/ace_fit.jl#L48

Would it be helpful, or just annoyingly complicated, if `ace_fit.jl` set all the known BLAS env vars for multithreading, i.e. `MKL_NUM_THREADS`, `OPENBLAS_NUM_THREADS`, maybe also plain `OMP_NUM_THREADS`, since some of the optimizers (namely the ones in `scikit-learn`) use those instead of the julia-internal value?

closed by #72

**Comment by wcwitt** [comment]
I think this is worth trying. I think (newer?) macs need `VECLIB_MAXIMUM_THREADS`

Likely relevant: https://stackoverflow.com/questions/30791550/limit-number-of-threads-in-numpy
