### ISSUE TITLE
integer dict keys

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACEpotentials.jl#73]
If the dict containing all the fitting params, which is passed to `ace_fit.jl`, is stored in a JSON, dict keys are all strings, and it appears that integer keys, which can be needed in `Dd`, for example, are not interpreted properly.  I haven't gone into the code, but from the resulting basis size it appears that they are simply ignored: I tried to do a 4,8 + 3,16 basis fit, and it was a really big basis, so I think it ended up doing 4,16 and ignored the limit indicated by `4: 8` dict entry.

I worked around it by saving the dict as YAML rather than JSON, and that worked fine, but since the code already finds tuples that are encoded as strings and converts them to tuples, perhaps dict keys that can be interpreted as integers should be converted to integers?  I guess that would require deciding that there's never a real reason to have a string key that contains only an integer.

Also, it would be nice if there was an error, rather than (apparently) silently ignoring the dict key.

**Comment by cortner** [comment]
latest interface (0.8) doesn't need integer keys. It should be possible to avoid those entirely. We are anyhow trying to increasingly simplify the user model specification. But if this or related issues arise we can look at it again.
