### ISSUE TITLE
Bug in the tutorial

### ISSUE THREAD

**Issue by tjjarvinen** [ACEsuit/ACEpotentials.jl#77]
There is a bug in "First example (Julia)" section of the tutorial.

Running, as instructed by the tutorial

```julia
using ACE1pack
import Random
using LinearAlgebra: norm, Diagonal

r0 = rnn(:Si)
basis = ace_basis(;
      species = :Si,
      N = 3,                        # correlation order = body-order - 1
      maxdeg = 12,                  # polynomial degree
      D = SparsePSHDegree(; wL=1.5, csp=1.0),
      r0 = r0,                      # estimate for NN distance
      rin = 0.65*r0, rcut = 5.0,    # domain for radial basis (cf documentation)
      pin = 2)

function gen_dat()
   sw = StillingerWeber()
   n = rand(2:3)
   at = rattle!(bulk(:Si, cubic=true) * n, 0.3)
   set_data!(at, "energy", energy(sw,at))
   set_data!(at, "forces", forces(sw,at))
   return ACE1pack.AtomsData(at, "energy", "forces")
end

Random.seed!(0)
train = [gen_dat() for _=1:20];
```

Generates following error:

```julia
ERROR: MethodError: no method matching ACE1pack.AtomsData(::Atoms{Float64}, ::String, ::String)
Closest candidates are:
  ACE1pack.AtomsData(::Atoms, ::Any, ::Any, ::Any, ::Any, ::Any) at ~/.julia/packages/ACE1pack/rq4n0/src/acefit.jl:12
Stacktrace:
 [1] gen_dat()
   @ Main ./REPL[7]:7
 [2] (::var"#1#2")(#unused#::Int64)
   @ Main ./none:0
 [3] iterate
   @ ./generator.jl:47 [inlined]
 [4] collect(itr::Base.Generator{UnitRange{Int64}, var"#1#2"})
   @ Base ./array.jl:787
 [5] top-level scope
   @ REPL[9]:1
```

On  a machine with:
```julia
julia> versioninfo()
Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
```

**Comment by wcwitt** [comment]
Thanks for reporting - I think this is because we need to tag a new version of ACEfit.

In the meantime, you could use the "stable" version  `https://acesuit.github.io/ACE1pack.jl/stable/`, which you can install with

```
using Pkg; Pkg.activate("."); pkg"registry add https://github.com/JuliaRegistries/General"; pkg"registry add https://github.com/JuliaMolSim/MolSim.git"; pkg"add ACE1pack@0.0, ACE1, JuLIP, IPFitting, ASE"
```

You could also try `dev`ing ACEfit to get the latest. I'll report back here once I thing things should be resolved.

**Comment by tjjarvinen** [comment]
I also should have added that I am just started to work for Christoph Ortner and my first task given by Christoph was to go trough the documentation and see, if everything is working and suggesting improvements. So, expect to get lots of issues and PRs from me in the future.

**Comment by cortner** [comment]
@wcwitt -- I'd like to clear up the bugs in the tutorials. A few local people at UBC are going to start learning how to use ACE1pack.jl and I'd rather not have the learn outdates syntax. 

What do you need from me? Should we just tag a new version of ACEfit? Or is there more to be done?

**Comment by wcwitt** [comment]
@cortner i think the best first step is to tag new versions. It might not solve everything, but it should allow the CI to pass.

CF: https://github.com/ACEsuit/ACEfit.jl/issues/37 and https://github.com/ACEsuit/ACE1pack.jl/issues/70

@tjjarvinen thanks for reporting and please continue to do so!

**Comment by cortner** [comment]
I've now tagged new versions of ACEfit (0.0.3) and ACE1pack (0.2.1) and this tutorial now runs on my system. @tjjarvinen can you please double-check and close if you think this is resolved?
