### ISSUE TITLE
documentation missing info on loading and saving potentials

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACEpotentials.jl#78]
Docs page https://acesuit.github.io/ACE1pack.jl/stable/ACE1pack/ace1pack_overview/ refers to `save_fit` with a link that doesn't mention it.

Nowhere, so far as I can tell, is it documented how to _load_ a saved json potential.

**Comment by cortner** [comment]
this is now documented for v0.8 (to be released asap)
