### ISSUE TITLE
Another Bug in the Tutorial

### ISSUE THREAD

**Issue by tjjarvinen** [ACEsuit/ACEpotentials.jl#79]
This bug is in [Fitting a TiAl potential (Julia)](https://acesuit.github.io/ACE1pack.jl/dev/literate_tutorials/TiAl/#Fitting-a-TiAl-potential-(Julia)) section of the tutorial. This same issue is also present in [TiAl potential (ACE1pack-julia)](https://acesuit.github.io/ACE1pack.jl/dev/literate_tutorials/ACE1pack_TiAl/#TiAl-potential-(ACE1pack-julia)) tutorial.

```julia
using ACE1pack
data_file = joinpath(ACE1pack.artifact("TiAl_tutorial"), "TiAl_tutorial.xyz")

data = JuLIP.read_extxyz(data_file)
train = data[1:5:end];

r0 = 2.88
ACE_B = ace_basis(species = [:Ti, :Al],
                  N = 3,
                  r0 = r0,
                  rin = 0.6 * r0,
                  rcut = 5.5,
                  maxdeg = 6);

Bpair = pair_basis(species = [:Ti, :Al],
                   r0 = r0,
                   maxdeg = 6,
                   rcut = 7.0,
                   pcut = 1, 	# this is not a reasonable default?
                   pin = 0)
B = JuLIP.MLIPs.IPSuperBasis([Bpair, ACE_B]);

Vref = OneBody(:Ti => -1586.0195, :Al => -105.5954)
weights = Dict(
        "FLD_TiAl" => Dict("E" => 30.0, "F" => 1.0 , "V" => 1.0 ),
        "TiAl_T5000" => Dict("E" => 5.0, "F" => 1.0 , "V" => 1.0 ))

train = [ACE1pack.AtomsData(t,"energy","force","virial",weights,Vref) for t in train]
```

Produces

```julia
ERROR: KeyError: key "default" not found
Stacktrace:
 [1] getindex
   @ ./dict.jl:498 [inlined]
 [2] ACE1pack.AtomsData(atoms::Atoms{Float64}, energy_key::String, force_key::String, virial_key::String, weights::Dict{String, Dict{String, Float64}}, vref::OneBody{Float64})
   @ ACE1pack ~/.julia/packages/ACE1pack/rq4n0/src/acefit.jl:30
 [3] (::var"#5#6")(t::Atoms{Float64})
   @ Main ./none:0
 [4] iterate
   @ ./generator.jl:47 [inlined]
 [5] collect(itr::Base.Generator{Vector{Atoms}, var"#5#6"})
   @ Base ./array.jl:787
 [6] top-level scope
   @ ~/Work/ace/tutorial-1.jl:32
```

On a machine with

```julia
julia> versioninfo()
Julia Version 1.8.3
Commit 0434deb161e (2022-11-14 20:14 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 4 on 4 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```

**Comment by cortner** [comment]
Quick workaround: 
```julia
weights = Dict(
        "default" => Dict("E" => 1.0, "F" => 1.0 , "V" => 1.0 ),
        "FLD_TiAl" => Dict("E" => 30.0, "F" => 1.0 , "V" => 1.0 ),
        "TiAl_T5000" => Dict("E" => 5.0, "F" => 1.0 , "V" => 1.0 ))

train = [ACE1pack.AtomsData(t,"energy","force","virial",weights,Vref) for t in train]
```
... but there are more problems with the tutorial, it seems it is very out of date ...

**Comment by cortner** [comment]
Actually, I just needed to first `dev ACE1pack, ACEfit` and then the rest of the tutorial works fine. 

Thought I think for a very first tutorial I would construct the solver as follows
```julia
using LinearAlgebra
q = 2.0
P = Diagonal(vcat(ACE1.scaling.(B.BB, q)...))
solver = ACEfit.RRQR(; rtol = 1e-5, P = P)
```

**Comment by cortner** [comment]
@wcwitt and @gelzinyte   --- could we try to bring ACE1pack and ACEfit to a state where we can tag both again so that the tutorials can be run without problems? I will help of course. We can continue on Slack.

**Comment by wcwitt** [comment]
@cortner i think the best first step is to tag new versions. It might not solve everything, but it should allow the CI to pass.

CF: https://github.com/ACEsuit/ACEfit.jl/issues/37 and https://github.com/ACEsuit/ACE1pack.jl/issues/70

@tjjarvinen thanks for reporting and please continue to do so!

**Comment by cortner** [comment]
I've now tagged new versions of ACEfit (0.0.3) and ACE1pack (0.2.1) and this tutorial now runs on my system. @tjjarvinen can you please double-check and close if you think this is resolved?

**Comment by tjjarvinen** [comment]
Yes, all the tutorials work now!
Closing this and #77.
