### ISSUE TITLE
Descriptor tutorial update

### ISSUE THREAD

**Issue by wcwitt** [ACEsuit/ACEpotentials.jl#81]
It looks like there is new descriptor functionality in ACE1: https://github.com/ACEsuit/ACE1.jl/commit/2470490b7ffa5638f1d7f1eb8679214e87139393.

We should update the corresponding ACE1pack tutorial: https://github.com/ACEsuit/ACE1pack.jl/blob/main/tutorials/descriptor.jl.

**Comment by ireaml** [comment]
Hi!
Is there any update on this? 
Was interested in using ACE to generate a structural descriptor, as exemplified in the [tutorial](https://acesuit.github.io/ACE1pack.jl/dev/literate_tutorials/descriptor/#ACE-Descriptors), but seems like it's broken. It mentions that an update to the pair potential implementation is required, but not sure which implementation this corresponds to?

Thanks very much!

**Comment by wcwitt** [comment]
Thanks for the interest, and yes. I’ll reply again tomorrow or Monday

**Comment by cortner** [comment]
Sorry for the dealy @ireaml  -- we have a lot of catching up to do all round. Please keep pinging us.

**Comment by wcwitt** [comment]
Ack, yes - I'm sorry as well. I'll make it a priority.

**Comment by cortner** [comment]
this is now done in #159 (actually in a relevant PR In ACE1.jl)
