### ISSUE TITLE
Polyenvelope

### ISSUE THREAD

**Issue by wcwitt** [ACEsuit/ACEpotentials.jl#82]
We need this in ACE1pack, although I don't know how it works in detail yet.

**Comment by cortner** [comment]
https://github.com/ACEsuit/ACE1.jl/blob/main/examples/newreg/tial_2.jl

**Comment by wcwitt** [comment]
Thanks, would you say this is the preferred way of doing things now?

**Comment by cortner** [comment]
for me, intuitively, yes. But I have far less experience than others (e.g. @casv2 ) with the practice of fitting potentials.

**Comment by casv2** [comment]
Yes I think this polyenvelope should be default

**Comment by cortner** [comment]
for the transform it is a little trickier: 
- if you have data for small r then you don't want the agnesi-transform I think
- if you do not have data for small r then I think you very much want the agnesi transform

But speaking more generally I wonder whether we need another careful conversation about htis.

**Comment by cortner** [comment]
This has all been in the ACE1x defaults for a while. Are we talking about bringing this into the JSON interface as well? Either way, I'd like to close this. 

Updating the JSON interface is a bigger job that can be a separate issue.

**Comment by wcwitt** [comment]
I think this was from before we had ACE1x in ACE1pack, so I agree with closing
