### ISSUE TITLE
Current Stable Documentation is not Working.  

### ISSUE THREAD

**Issue by tjjarvinen** [ACEsuit/ACEpotentials.jl#83]
The documentation section that points to stable version is not working. Because it point to an ancient version. This is an issue because it is the version that is linked from the main GitHub page. For new people starting with ACE this is big issue, as it can cause a lot of confusion with non working documentation.

There are two possible fixes

1. Remove the links to the stable version and have all links point to the developer version.
2. Tag version to GitHub, which will trigger stable version build for the documentation.

Option 2. is probably the best way, as it does not need anything else than a tag in the repo.

**Comment by cortner** [comment]
Thank you for bringing this up  -  It's been on my todo list for a long time to sort out the doc builds. Can we discuss later when we meet please?

**Comment by wcwitt** [comment]
Only have time for a quick reply, but some of this was deliberate. The "ancient" version is just the ACE1pack with IPFitting, which we've kept alive because some people weren't ready to switch to ACEfit. So the idea was that the `stable` docs would be those.

But I think it's time to move past that and I agree wholeheartedly with the overall point about making things less confusing for users!

**Comment by wcwitt** [comment]
Also agree that we should always tag github releases to coincide with julia releases - that's key for version-specific docs. This is something we can do retroactively

**Comment by cortner** [comment]
If the two of you want to coordinate setting this up properly, I'll be really grateful. Do you need any additional access for that?

**Comment by wcwitt** [comment]
Thanks @tjjarvinen for the PR. At this point I likely won't have time to review it carefully until after the holidays, but do feel free to keep improving things as you see fit and I'm happy to review it all at once then.
