### ISSUE TITLE
basis1p_params referred to but doesn't seem to exist

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACEpotentials.jl#9]
https://github.com/ACEsuit/ACE1pack.jl/blob/b1505b8d8e5ac500fcce8e8216b4c3fd41dfe223/src/basis.jl#L40

This argument type does not seem to be documented anywhere or to exist. Is it now called `rad_basis`?

**Comment by gelzinyte** [comment]
Yas, that's now `rad_basis`. I'll update the docstrings.

**Comment by gelzinyte** [comment]
Fixed in #28
