### ISSUE TITLE
Vref in data

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpotentials.jl#90]
At the moment the tutorial converts data as follows: 
```julia 
ACE1pack.AtomsData(atoms, "energy", "force", "virial", weights, Vref)
```
I understand that the weights Dict will specify the weight for that training structure. This is a nice way to do it. 

But I don't understand why `AtomsData` needs to know about `Vref`? That seems extremely unnatural.

**Comment by wcwitt** [comment]
I don't find it too unnatural for `AtomsData` to contain reference energies (e.g., isolated atom energies), which is all that is stored. In principle there could also be reference forces and virials, etc.

Roughly, I think of `AtomsData` (and `ACEfit.AbstractData` more generally) as containing everything required to enable
```
submatrix = feature_matrix(d::AtomsData, basis)
subvector = target_vector(d::AtomsData)
```

I have considered changing the ACEfit syntax to something like
```
feature_matrix(d::AbstractData, basis; kwargs...)
target_vector(d::AbstractData; kwargs...)
```
in which case `AtomsData <: AbstractData` could depend on less. We can do that if you prefer.

**Comment by cortner** [comment]
Logically/conceptually what bothers me is that this is part of the model and not part of the data. We have an affine model not a linear model.

**Comment by wcwitt** [comment]
I'm a little confused then - what abstract structure do you have in mind?

**Comment by cortner** [comment]
I just don't want to conflate model and data. I have two suggestions: 

(1) keep separate `data, basis, Vref` 

(2) get rid of `basis` and just have `data, model` -- of course internally `model = (basis, Vref)` but that's an implementation detail.

**Comment by cortner** [comment]
I posted on slack...

**Comment by cortner** [comment]
I think we won't fix this for a while - the current code is now pretty much settleed...
