### ISSUE TITLE
pace export writes files that LAMMPS thinks are invalid

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACEpotentials.jl#93]
An ACE potential exported by 
```
            stat = os.system(f"""julia -e 'import ACE1pack; IP = ACE1pack.read_dict(ACE1pack.load_dict("{pot_file}")["IP"]); """
                             f"""ACE1pack.ExportMulti.export_ACE("{pot_file}.yace", IP, export_pairpot_as_table=true)' """)
```
gives the following error when read in by LAMMPS
```
terminate called after throwing an instance of 'YAML_PACE::TypedBadConversion<int>'
  what():  yaml-cpp: error at line 50, column 8: bad conversion
Aborted (core dumped)
```

The relevant lines (1-based numbering) of the yaml file are
```
    46      r0: 2
    47      xr: 1.6666666666666665
    48      maxn: 10
    49      pr: 2
    50      p: 1.0
    51    [2, 1]:
    52      rcut: 8.0
    53      xl: 0.3333333333333333
    54      recursion_coefficients:
    55        B:
```
I guess it's the float `p` field.

Is this sufficient, or do you need a json for debugging?

**Comment by bernstei** [comment]
I suspect it was caused by passing a poor choice of parameter types to some transform in the julia basis-creation code, but it would be good if ACE's export guaranteed that parameters were of the correct type when exporting.

**Comment by cortner** [comment]
I believe our PACE export has been fixed. If not, then please re-open ..
