### ISSUE TITLE
Rename `export_ace`

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpotentials.jl#96]
I suggest renaming `export_ace` to `export_lammps` or `export2lammps` or something like it so that the function call becomes self-documenting. 

@tjjarvinen @casv2 @WillBaldwin0  : please let me know what you think, what name would you like and then Will or Cas can you make a PR after we agree please?

**Comment by tjjarvinen** [comment]
I think `export2lammps` is the best option. Or maybe `export_to_lammps`.

**Comment by cortner** [comment]
I think this has been done a while ago.
