### ISSUE TITLE
Redesign `linear_errors`

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEpotentials.jl#98]
It appears that `linear_errors` prints the table to the standard output stream and then returns a Dict. In some scenarios this is problematic. E.g. the Documenter tutorials won't show the printed output, only the `Dict`.  I wonder, whether linear_errors should produce a custom type, and that printing of the output can be enfroced with `display`.

While we are discussing this -- why call this `linear_errors`? What is linear about it?  Don't we just evaluate the model on the test set?

**Comment by wcwitt** [comment]
I didn't spend much time on this routine and it is in desperate need of a refactor. I will start by adding the `display` option you mention.

The name is a bit silly and we should change it, particularly if we can now dispatch on `acemodel`.

**Comment by cortner** [comment]
before you charge in, can you propose the new naming here?

**Comment by wcwitt** [comment]
Doesn't really matter to me:

`errors(model::acemodel, data::AbstractVector{AtomsData})`?

`error_table`? `compute_errors`?

**Comment by wcwitt** [comment]
@cortner, do you still want to weigh in before I make some changes?

**Comment by cortner** [comment]
My suggestion: 
- define a type ACEErrorTable which just wraps the two dicts
- allow additional dicts for train and test within a single structure
- display should show everything - both RMSE and Mae, train and test. 
- define display_rmse, display_mae, display_rmse_train, ... to show just partial information.
- instead of compute_errors use error_table(train, test, model)

This is the basic functionality and we can start adding to it from here?

**Comment by cortner** [comment]
Btw - it's unclear to me whether this should be in ACEfit or in ACE1pack? Maybe the former?

**Comment by cortner** [comment]
For now I've added a verbose option to `linear_errors` that prevents printing and the option to print the tables from the Dict. 

I think we can close this and figure out a better more general structure at some unspecified point in the future...
