### ISSUE TITLE
Verbose parameter names for `acemodel`

### ISSUE THREAD

**Issue by gelzinyte** [ACEsuit/ACEpotentials.jl#99]
In `acemodel` there are pairs of parameters for ace (radial) basis and pair basis. I think instead of naming them `maxdeg` and `maxdeg2` it would be much clearer to name them `ace_maxdeg` and `pair_maxdeg`, `ace_radial_rcut`, `pair_rcut`, for example.

**Comment by cortner** [comment]
I'm going to be a little difficult on this and apologize beforehand :). It's an important issue though and if there is enough push from everybody then I might just give in to peer pressure...

The Julia style tends to avoid overly verbose names. I can see the argument for replacing `rcut2` with `rcut_pair` but not for replacing `rcut` with `ace_radial_rcut`. (etc)  I think the general question is whether we should use 
* verbose "computer science style" argument names.
* briefer "mathematics style" argument names.
Depending on how we decide we may need to make several more changes to the interfaces.

Maybe we need more voices? I'd really appreciate the feedback.

CC @tjjarvinen @wcwitt @jameskermode @casv2 @WillBaldwin0 @gabor1

**Comment by jameskermode** [comment]
Doesn't have to be an either/or. Could have the best of both worlds with more verbose synonyms for the current short names, which would retain backwards compatibility. We do this in QUIP/GAP.

**Comment by cortner** [comment]
So Plots.jl does this too but doesn't that lead to a lot of extra maintenance work? And does it not get confusing for users?

**Comment by cortner** [comment]
Trying to setup a poll on this ... 

/polls "verbose" "succinct" "both"

**Comment by jameskermode** [comment]
I can see that argument, but if it’s essentially a symbolic link at parameter reading time then there shouldn’t be much additional maintenance. However I guess we’re talking about function arguments here rather than an input file so there might not be a clean way to do that.

**Comment by cortner** [comment]
I think there is one important issue here: right now the Julia interface uses different keyword arguments from the JSON interface and this could definitely become confusing for users who use both. So maybe we should take the "both options" idea seriously.

**Comment by gelzinyte** [comment]
I think some verbosity is required by the fact that we have two sets of identically named parameters. I think that would make it slightly more intuitive & nicer to use.  How about adding `ace_` and `pair_` to the duplicate names to signify where they are going to? (on a better look `ace_radial_rcut` has "radial" twice...). 

Do you have examples of different keywords? Apart from the top layer of the JSON dictionary and an occasional key (in particular "type") all the parameters in JSON/ACE1pack are converted to kwargs and given to ACE1 functions directly, so it should all be the same. So is this an `acebasis` vs `acemodel` issue? Should we support one?

**Comment by cortner** [comment]
I *really* don't like `ace_rcut` is because the function is already called `acebasis` or `acemodel` so why say it again. But your argument also makes sense ... I don't know what a good solution is.

**Comment by wcwitt** [comment]
On the general point, I'm with Elena. I typically find the Julia style a little too terse.

On the specific case of `ace_rcut`, I could accept `rcut` provided the the other is changed to `pair_rcut`.

> I don't know what a good solution is.

I think the only solution is for us to argue about it for a while and then move on.

**Comment by cortner** [comment]
> I think the only solution is for us to argue about it for a while and then move on.

👍

**Comment by gelzinyte** [comment]
Main issue was with the `sth` and `sth2` pairs, so `pair_rcut` and `rcut` would work.

**Comment by cortner** [comment]
Trying to revive this discussion ... I'm happy moving to `pair_***`; we can just agree on that. 

Beyond that, do we want "symbolic link" type multiple possible choices for the keyword arguments? I'm a bit nervous about this.

**Comment by wcwitt** [comment]
I'm openminded about it, but would vote against right now.

**Comment by cortner** [comment]
I think this is essentially settled. If specific parameter names should be changed or aliases added, please file separate issues.
